TwitchLib/TwitchLib

TwitchLib/TwitchAPI.cs
MakeGetRequest in TwitchApi class returns response streams as Encoding.ASCII when it should be Encoding.UTF8
=> WebRequests read as Encoding.ASCII instead of Encoding UTF8

TwitchLib/ChatMessage.cs
Check message text to see if it's bounded by 0x01s. Additionally (to be
absolutely sure) check for the presence of the "ACTION ". If both are
found, strip that metadata and set a new flag (called ActionFlag) to true.
I don't actually know if it's better to strip the metadata or not, but I can't see a use case for leaving it especially when users need only check a boolean property to apply different logic for these messages.
Associated issue: https://github.com/swiftyspiffy/TwitchLib/issues/15
=> [#15] Updated ChatMessage.cs to handle /me text.

TwitchLib/ChatMessage.cs, TwitchLib/MessageEmote.cs, TwitchLib/TwitchChatClient.cs, TwitchLib/TwitchLib.csproj
Added support for emote replacement in chat messages. Care was taken to ensure compatibility with existing codebases. Tried to be thorough in documenting. There's probably some mixed coding style, couldn't decide between the current _private + Accessor method or the upcoming Accessor-only style and had an oddball case or two that just wouldn't work with the newer one.
I'm working from an actual project now so this is much more QA'd than the last one ;)
"Test framework" (I added some lines to the example app, it's not unit testing or anything) is available here: https://github.com/GlitchHound/TwitchLib/tree/message_emotes_example
=> Message emotes

TwitchLib/TwitchPubSub.cs
Added the following actions:
- onSubscribers (sender, onSubscribersArgs) // Room put into subscribers-only mode
- onSubscribersoff (sender, onSubscribersoffArgs) // Subscribers-only mode disabled
- onClear (sender, onClearArgs) // Chat was cleared by a moderator
- onEmoteonly (sender, onEmoteonlyArgs) // Room put into emoteonly mode
- onEmoteonlyoff (sender, onEmoteonlysoffArgs) // Emote-only mode disabled
- onR9kbeta (sender, onR9kbetaArgs) // Room put into r9kbeta mode
- onR9kbetaoff (sender, onR9kbetaoffArgs) // R9kbeta mode disabled
=> Added missing moderator actions

TwitchLib/TwitchClient.cs
duration.seconds was returning 0 if the time was a multiple of 60.
For example a timeout with a duration of 600 Seconds would result in a time of 0 seconds.
=> Fixed Timeout duration

TwitchLib/TwitchClient.cs
If the TCP connection is silently cut the client thinks it is still listening to these channels.
I don't know whether it should fire "OnClientLeftChannel" or not.
OnClientLeftChannel fires only when a client _successfully_ leaves a channel.
=> Clear JoinedChannels at Disconnected event.

TwitchLib/Internal/TwitchAPI.cs, TwitchLib/Models/API/ChannelSubscribersResponse.cs, TwitchLib/Models/API/Subscription.cs, TwitchLib/TwitchAPI.cs, TwitchLib/TwitchLib.csproj
I noticed yesterday that the project has been restructured considerably since I initially checked this months ago. 
Looking great now, well done =)
I made the decision to ditch my library and switch to this tonight for my Streamers bot, however during implementation I noticed a method I needed was missing. The ability to pull a full list of subscribers rather than making multiple API calls to check whether a user was a subscriber or not.
I've added it. Tried to keep it inline with your current restructuring. You may decide to add or may have left out for a reason, but it's here if you decide to merge :)
Returns a Response with List of type User,  and int (Count)
=> Adds sync/async GetAllChannelSubscribers

TwitchLib/Internal/WebSocketClient.cs, TwitchLib/TwitchLib.csproj, TwitchLib/TwitchPubSub.cs, TwitchLib/packages.config
Feel free to clean it up a bit, I put it together on a train :P
May need a bit more testing.
It's a start at making TwitchLib .Net Core compatible, as System.Net.Websockets.Client is .Net Standard 1.3 and Mono compatible.
Maybe we can look at Meebey next, and get an internal IrcClient written.
**WARNING: it does change the target client profile to .Net 4.6**
=> Switched to .Net Standard 1.3 compatible Websocket library

TwitchLib/TwitchClient.cs
Hey, I've made small change to the code that fixes issue when there is no channel parameter provided in constructor of TwitchClient class.
=> Small bug fix for null in TwitchClient constructor for null channel parameter

TwitchLib/Models/PubSub/Responses/Message.cs, TwitchLib/Models/PubSub/Responses/Messages/ChannelBitsEvents.cs, TwitchLib/TwitchPubSub.cs
Updating channel-bitsevents to channel-bits-events-v1
Changing how Listen works to compile a list of events to listen to before firing the entire Listen off in one request, because you're going to be specifying the same Oauth key to all of the listen requests anyways.
=> Bit Events and Listen

TwitchLib.Testing/Application.API/TwitchLib-API-Tester/Application.API.csproj, TwitchLib.Testing/Application.ClientAndPubSub/TwitchLib-Client-PubSub-Tester/Application.ClientAndPubSub.csproj, TwitchLib/TwitchClient.cs
There was a missing else keyword in logging initialisation. I replaced the if-else statement with a null-coalescing operator. Much cleaner. Added missing refs to the test projects.
=> Fix logging initialization, and added missing refs.

TwitchLib/Events/Client/OnConnectedArgs.cs, TwitchLib/Events/Client/OnConnectionErrorArgs.cs, TwitchLib/Events/Client/OnDisconnectedArgs.cs, TwitchLib/Events/Client/OnJoinedChannelArgs.cs
A couple events already had BotUsername.
Changed 4 events from Username > BotUsername
This could be less confusing to anyone using the lib.
This is a breaking change.
=> Inconsistant Parameters in Client events for BotUsername (Breaking)

TwitchLib/Services/LiveStreamMonitor.cs
I'm a member of the Pinguem.ru competition on finding errors in open source projects. A bug found using PVS-Studio. Warnings:
[V3031](https://www.viva64.com/en/w/v3031/) An excessive check can be simplified. The '||' operator is surrounded by opposite expressions '!_isStartup' and '_isStartup'. LiveStreamMonitor.cs 161
[V3031](https://www.viva64.com/en/w/v3031/) An excessive check can be simplified. The '||' operator is surrounded by opposite expressions '!_isStartup' and '_isStartup'. LiveStreamMonitor.cs 175
[V3031](https://www.viva64.com/en/w/v3031/) An excessive check can be simplified. The '||' operator is surrounded by opposite expressions '!_isStartup' and '_isStartup'. LiveStreamMonitor.cs 184
=> Fix V3031 warnings from PVS-Studio Static Analyzer

TwitchLib/Models/Client/ChatCommand.cs, TwitchLib/TwitchClient.cs
I'm a member of the Pinguem.ru competition on finding errors in open source projects. A bug found using PVS-Studio. Warnings:
[V3022](https://www.viva64.com/en/w/v3022/) Expression 'chatMessage.Message.Replace(chatMessage.Message.Split(' ')?[0] + " ", "")' is always not null. The operator '??' is excessive. ChatCommand.cs 28
[V3022](https://www.viva64.com/en/w/v3022/) Expression 'whisperMessage.Message.Replace(whisperMessage.Message.Split(' ')?[0] + " ", "")' is always not null. The operator '??' is excessive. TwitchClient.cs 901
=> Fix V3022 warnings from PVS-Studio Static Analyzer

TwitchLib/Services/LiveStreamMonitor.cs
Added return type Task on _getUserIds() instead of void
Added _getUserIds.Wait() so function doesn't return asynchronously
=> Fixed problem where starting LiveStreamMonitor might happen before service returned from TwitchAPI getting UserIds

TwitchLib/Models/API/v5/Auth/RefreshResponse.cs
Added ExpiresIn field to Refresh model.. forgot that during the initial create bcs the twitch docs dont show its actually there.. but it is and its needed
=> Added ExpiresIn field to Refresh model

TwitchLib/Events/Client/OnFailureToReceiveJoinConfirmationArgs.cs, TwitchLib/Exceptions/Client/FailureToReceiveJoinConfirmationException.cs, TwitchLib/TwitchClient.cs
Stuff was added twitce to the JoinedChannels List and the awaiting joins list ran empty at some point and produced a null entry in the JoinedChannels list that then caused a Null Ref Exception while iterating
This should be fixed with this.
Would like you to run a test too tho just to be sure.
=> Added Fixed Not Exisiting Channel Check back

TwitchLib/Models/API/Helix/StreamsMetadata/Overwatch.cs
Issue prevents stream metadata for overwatch working correctly.
=> Fix PlayerHearthstone in Overwatch Stream Metadata

TwitchLib/Events/Client/OnGiftedSubscriptionArgs.cs, TwitchLib/Events/Client/OnLogArgs.cs, TwitchLib/Events/Client/OnRaidNotificationArgs.cs, TwitchLib/Events/Client/OnRitualNewChatterArgs.cs, TwitchLib/Events/Client/OnUnaccountedForArgs.cs
Noticed that some client events don't inherit EventArgs. Do not know if this was on purpose, yet I updated each file to follow the standard that other events have set. Also keeping it consistent over all events.
=> Noticed that not all events inherit EventArgs

README.md
=> Fix link to TwitchLib.Extension Readme
