TwitchLib/TwitchLib

- TwitchLib/TwitchLib.csproj
- TwitchLib/WhisperMessage.cs
Fixed Path to SmartIRC4net.dll
> Fixed Problem with Whispers when IRCString includes Badges

- TwitchLib/ChannelState.cs
- TwitchLib/ChatMessage.cs
- TwitchLib/ConnectionCredentials.cs
- TwitchLib/Exceptions/ErrorLoggingInException.cs
- TwitchLib/TwitchAPI.cs
- TwitchLib/TwitchAPIClasses/Chatter.cs
- TwitchLib/TwitchAPIClasses/Subscription.cs
- TwitchLib/TwitchAPIClasses/TwitchChannel.cs
- TwitchLib/TwitchAPIClasses/TwitchFollower.cs
- TwitchLib/TwitchAPIClasses/TwitchStream.cs
- TwitchLib/TwitchAPIClasses/TwitchTeamMember.cs
- TwitchLib/TwitchAPIClasses/TwitchVideo.cs
- TwitchLib/TwitchChatClient.cs
- TwitchLib/TwitchIpAndPort.cs
- TwitchLib/TwitchWhisperClient.cs
- TwitchLib/WhisperMessage.cs
- Remove some more unneeded code.
- Use VS documentation to document TwitchAPI, TwitchChatClient and TwitchWhisperClient functions and events.
- Improve parsing of certain objects to prevent exceptions [partially UNTESTED, please take your time to review].
- Improve TwitchAPI functions by not reusing as much code [partially UNTESTED, please take your time to review].
- Improve parameter naming in TwitchAPI (username -> channel where applicable).
- Enum integer binding is cool and reduces ifs, switches etc.
Again, this commit is partially UNTESTED and could break certain things. Please take your time to review this commit and make sure everything works. Also, the events got more fitting names so some things will be broken for some existing users. Make sure to notify your userbase of this. …
> (Partially) redo some files and add documentation.

- TwitchLib/ChannelState.cs
- TwitchLib/ChatMessage.cs
- TwitchLib/Common.cs
- TwitchLib/TwitchAPI.cs
- TwitchLib/TwitchChatClient.cs
Events, representing hosting start and hosting stop were added. Also, some classes that obviously should static were marked as static.
> Hosting detection added

- TwitchLib/TwitchPubSub.cs
Added moderation action "untimeout".
/untimeout removes the timeout of timedouted Users. This has no effect on banned users.
Added Event onUntimeout(sender, onUntimeoutArgs)
> Added moderation action "untimeout"

- README.md
- TwitchLib/ChatParsing.cs
- TwitchLib/Events/Client/OnExistingUsersDetectedArgs.cs
- TwitchLib/Events/Client/OnUserBannedArgs.cs
- TwitchLib/Events/Client/OnUserJoinedArgs.cs
- TwitchLib/Events/Client/OnUserLeftArgs.cs
- TwitchLib/Events/Client/OnViewerTimedoutArgs.cs
- TwitchLib/TwitchClient.cs
- TwitchLib/TwitchLib.csproj
> Makes requested changes.

- README.md
- TwitchLib/Common.cs
- TwitchLib/Exceptions/API/StreamOfflineException.cs
- TwitchLib/Properties/AssemblyInfo.cs
- TwitchLib/TwitchAPI.cs
- TwitchLib/TwitchLib.csproj
- TwitchLibExample/TwitchLibExample/Form1.cs
Makes suggested changes as stated in #84
> Makes adjustments in TwitchAPI and Exceptions

- TwitchLib/Internal/TwitchAPI.cs
- TwitchLib/Models/API/StreamsSummary.cs
- TwitchLib/Models/Client/ChatCommand.cs
- TwitchLib/Services/FollowerService.cs
- TwitchLib/TwitchAPI.cs
- TwitchLib/TwitchClient.cs
- TwitchLib/TwitchLib.csproj
- TwitchLibExample/TwitchLibExample/Form1.Designer.cs
- TwitchLibExample/TwitchLibExample/Form1.cs
I'll leave this open for a few days for comments.
> Twitch API Reorganization #2

- TwitchLib/Internal/Rfc2812.cs
- TwitchLib/Internal/WebSocketClient.cs
- TwitchLib/Models/Client/ConnectionCredentials.cs
- TwitchLib/TwitchClient.cs
- TwitchLib/TwitchLib.csproj
- TwitchLibExample/TwitchLibExample/App.config
- TwitchLibExample/TwitchLibExample/Properties/Resources.Designer.cs
- TwitchLibExample/TwitchLibExample/Properties/Settings.Designer.cs
- TwitchLibExample/TwitchLibExample/TwitchLibExample.csproj
- WebsocketTestClient/WebsocketTestClient/App.config
- WebsocketTestClient/WebsocketTestClient/Program.cs
- WebsocketTestClient/WebsocketTestClient/Properties/AssemblyInfo.cs
- WebsocketTestClient/WebsocketTestClient/WebsocketTestClient.csproj
- WebsocketTestClient/WebsocketTestClient/WebsocketTestClient.sln
- WebsocketTestClient/WebsocketTestClient/packages.config
Switched to the web socket wrapper for the actual IRC connection.
I added a very basic test console client for your evaluation.
This is what I mentioned at the end of the issue I opened regarding a port of SmartIrc4net to .NetStandard.
This is just here for evaluation now, would need to leave it running for a while, log messages / message counts with both clients and see how it holds up. It's basically the implementation twitch use themselves on the website.
Gets you down to 0 non Microsoft dependencies =)
(Well.. Newtonsoft.Json, but still :P)
> Ditched Meebey Entirely

- TwitchLib/Internal/TwitchAPI.cs
- TwitchLib/Internal/WebSocketClient.cs
- TwitchLib/Models/Client/MessageEmote.cs
- TwitchLib/TwitchClient.cs
- WebsocketTestClient/WebsocketTestClient/Program.cs
- WebsocketTestClient/WebsocketTestClient/WebsocketTestClient.csproj
- WebsocketTestClient/WebsocketTestClient/WebsocketTestClient.sln
Causing parse errors by not splitting the buffered output into individual lines.
> Fixed the bug in WebSocketClient

- TwitchLib/Services/FollowerService.cs
Hello!
Commits description will tell all what you need to know =)
> Crash fix and some comments

- TwitchLib/Models/API/v5/User.cs
> v5 user ID should be string

- TwitchLib/Models/Client/ChatMessage.cs
- TwitchLib/Models/Client/MessageEmote.cs
Hopefully start to fix emotes by now having them report the correct url. They still don't seem to work through EmoteReplacedMessage though
> Start to Fix emotes

- TwitchLib/Exceptions/Services/UnitializedChannelListException.cs
- TwitchLib/Services/LiveStreamMonitor.cs
- TwitchLib/TwitchLib.csproj
- appveyor.yml
Hiya,
Was updating my clone of this library and I noticed several different references broken in the VS Solution. Hopefully this should add most of them back. Also ignore the appveyor stuff, I was messing around with that build process; feel free to squash all of my commits.
Thanks!
> Fix VS Project References

- README.md
This fixes another code sample mistake I found and posted in #199 but got deleted from the description when I was editing it.
> Fixed more code sample mistakes

- TwitchLib-API-Tester/TwitchLib-API-Tester/Form1.Designer.cs
- TwitchLib-API-Tester/TwitchLib-API-Tester/Form1.cs
- TwitchLib-Client-PubSub-Tester/TwitchLib-Client-PubSub-Tester/Form1.cs
- TwitchLib/Events/Client/OnBeingHostedArgs.cs
- TwitchLib/Internal/TwitchAPI/v5.cs
- TwitchLib/Models/API/v5/Badges/BadgeContent.cs
- TwitchLib/Models/API/v5/Bits/Action.cs
- TwitchLib/Models/API/v5/Bits/Cheermotes.cs
- TwitchLib/Models/API/v5/Bits/DarkImage.cs
- TwitchLib/Models/API/v5/Bits/Images.cs
- TwitchLib/Models/API/v5/Bits/LightImage.cs
- TwitchLib/Models/API/v5/Bits/Scales.cs
- TwitchLib/Models/API/v5/Bits/Tier.cs
- TwitchLib/Models/API/v5/Channels/Channel.cs
- TwitchLib/Models/Client/ChatMessage.cs
- TwitchLib/TwitchAPI.cs
- TwitchLib/TwitchClient.cs
- TwitchLib/TwitchLib.csproj
+ Tested under .NetStandard 2.0 preview 2.
> Housekeeping

- TwitchLib/Models/Client/Subscriber.cs
- TwitchLib/Models/Client/WhisperMessage.cs
Hey swifty :)
I found 2 things you forgot about while changing the Id to string only representation and thought I would fix them for you ;)
Regards
Syzuna
> Update two Client Models to conform id changes

- unity.md
Small change to fix broken link in guide.
> Fix broken link.

- TwitchLib/Internal/TwitchAPI/v5.cs
- TwitchLib/TwitchAPI.cs
Set communities means Set Community is now obsolete
> Add Set Communities to the API

- TwitchLib/Events/PubSub/OnBanArgs.cs
- TwitchLib/Events/PubSub/OnTimeoutArgs.cs
- TwitchLib/Models/PubSub/Responses/Messages/ChatModeratorActions.cs
- TwitchLib/TwitchPubSub.cs
Only on Ban and Timeout. User is Null on UnBan and UnTimeout :(
> Adds Username to PubSub Ban and Timeout

- TwitchLib.Testing/Application.API/TwitchLib-API-Tester/Application.API.csproj
- TwitchLib.Testing/Application.AuthFlowExample/Application.AuthFlowExample.csproj
- TwitchLib.Testing/Application.ClientAndPubSub/TwitchLib-Client-PubSub-Tester/Application.ClientAndPubSub.csproj
Not the Build Debug Library File, but the actual projects
> Fixes Reference Paths in Separate Project files to Actual Project

- TwitchLib/Events/PubSub/OnStreamDownArgs.cs
- TwitchLib/Models/PubSub/Responses/Messages/VideoPlayback.cs
- TwitchLib/TwitchPubSub.cs
Hello,
this should fix the pubsub issues users including me reported the last days
Regards
Syzuna
> PubSub changes based on Issue feedback

- .travis.yml
- TwitchLib.sln
- TwitchLib/Models/Client/ChatMessage.cs
- TwitchLib/Models/Client/SubscriberBase.cs
- TwitchLib/Models/Client/WhisperMessage.cs
- TwitchLib/TwitchLib.csproj
Unity3d will eventually support .Net Standard 2.0 (in the next few months according to roadmap) - However - right now it doesn't
> Now also .Net 4.5.2 Compatible. Re-Adds unity3d Compatibility

- TwitchLib/Api/Sections/Videos.cs
This pull request fixes some of the issues mentioned in #295.
Specifically the video segmentation has been fixed and a given video file is no longer completely read into memory.
> Video upload fixes

- TwitchLib/TwitchLib.csproj
Hey,
Just a quick change to the csproj to fix the multibuild feature :D
Regards
Syzuna
> Fixing Multibuild

- TwitchLib/Services/LiveStreamMonitor.cs
- Channel List now a ReadOnlyCollection so it cant be changed from outside the Service anymore
- Check if there was atleast 1 channel added to the monitoring list ... if not it now throws an UnintializedChannelListException if you call StartService
- various styling fixes
- fixed a "suspisious equals operation" (VS yelled at me)
Regards 
Syzuna and LuckyNoS7evin ;)
> Changes to LiveStreamMonitor Service

- TwitchLib/Api/Sections/Auth.cs
- TwitchLib/Api/TwitchAPI.cs
- TwitchLib/Exceptions/API/TokenExpiredException.cs
- TwitchLib/Models/API/v5/Auth/RefreshResponse.cs
Ok here is the new PR based on the latest changes.
I need to learn some git stuff ^^
> ExpiredTokenException and Token Refresh Method for the API

- TwitchLib/Services/MessageThrottler.cs
All outgoing messages from the Client would be blocked, kinda not cool :D
> Whoops! Original Queue start was Blocking!!

- TwitchLib/Api/TwitchAPI.cs
- TwitchLib/RateLimiter/BypassLimiter.cs
Also Allows custom rate periods, as well as disabling / bypassing the rate limiter.
> Allow passthrough of a singleton ratelimit object.

- TwitchLib/Api/Sections/Auth.cs
- TwitchLib/Interfaces/ITwitchAPI.cs
Hey swifty,
found some small things I forgot while redoing the PR for the new code base.
This includes that I didnt include the new Section to the API interface and forgot to add ConfigureAwait(false) to dont cause UI deadlocks for the Post Request.
(I have no clue why github fails to do the diffs for me...)
Regards
Syzuna
> Fixed some minor stuff for Auth API section

- TwitchLib/Api/Sections/Webhooks.cs
Changed Follow Webhook URL to conform recent released changes from Twitch as announced on the TwitchDev TwitchApp server
> Changed Follow Webhook URL to new schema

- TwitchLib/Extensions/Client/FollowersOnlyExt.cs
Fixed wrong method name for FollowersOnlyOn
You copy pasted to fast there :P
> Fixed wrong method name for FollowersOnlyOn

- TwitchLib/Api/Sections/Videos.cs
This will address https://github.com/swiftyspiffy/TwitchLib/issues/349.
> Fix Helix GET videos logic bug around optional fields

- TwitchLib.Extension/README.md
Add a not that we supporting it in discord for a little bit (me) and then modified to match the current release
> Change the README for extensions

- README.md
> Added Webhook repo to About

- README.md
- Changed to new format (rewrite)
- Made it a usable class (for easy copy pasta) to avoid questions.
- Note: I did not verify all the events. I will do this tonight.
> Updated Client example

- README.md
- Added Required core for webhook
- Fixed brackets in Client example that were annoying me.
- Supplied updated example for API / Pubsub.
> Updating some examples to latest.

- README.md
Loaded up the example code noticed errors. Fixed.
> Updated Client example.

- README.md
Changed e.Subscriber.Channel to e.Channel as per #26 pr.
> Updated Client Channel parameter for new sub arg change

- README.md
Updated API
- Old initialize to api.settings
> Updated examples for Nuget 2.1.1

- README.md
Now includes a simple entry point.
The code has been tested.
> Update client example

- README.md
Feel free to comment etc.... just trying to update to at least have no syntax errors
> Updated Client doc example to V3

- README.md
Could use some changes for helix, but for now fixed to work with proper namespaces
> Updated API doc example to V5

- README.md
Few extra cleanup to apply capitalized standard to event names.
> Add OnLog to client example / Added VB example

- README.md
C# code sample had rogue tab spacing
> Update README.md to standardize spacing

- README.md
> removed rooms support

- README.md
> small note

- README.md
Not starting known verified bot is required for sending whispers
> Add whisper note

- README.md
I did not verify these calls, FYI.
> Removed v5 from API Example

- README.md
> updated docs links in readme
